// flow-typed signature: 56cefb03d637ec6e070b70e4d1511304
// flow-typed version: <<STUB>>/clone_v^2.1.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'clone'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'clone' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'clone/clone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'clone/clone.js' {
  declare module.exports: $Exports<'clone/clone'>;
}
