// flow-typed signature: 1c46bfad2a39e2c63992b41c1d6bb875
// flow-typed version: <<STUB>>/kleio_v^1.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kleio'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kleio' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kleio/dist/index' {
  declare module.exports: any;
}

declare module 'kleio/dist/kleio' {
  declare module.exports: any;
}

declare module 'kleio/src/index' {
  declare module.exports: any;
}

declare module 'kleio/src/kleio' {
  declare module.exports: any;
}

declare module 'kleio/test/kleio-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kleio/dist/index.js' {
  declare module.exports: $Exports<'kleio/dist/index'>;
}
declare module 'kleio/dist/kleio.js' {
  declare module.exports: $Exports<'kleio/dist/kleio'>;
}
declare module 'kleio/index' {
  declare module.exports: $Exports<'kleio'>;
}
declare module 'kleio/index.js' {
  declare module.exports: $Exports<'kleio'>;
}
declare module 'kleio/src/index.js' {
  declare module.exports: $Exports<'kleio/src/index'>;
}
declare module 'kleio/src/kleio.js' {
  declare module.exports: $Exports<'kleio/src/kleio'>;
}
declare module 'kleio/test/kleio-test.js' {
  declare module.exports: $Exports<'kleio/test/kleio-test'>;
}
