// flow-typed signature: cf3d6cdffe335aeee4bde552d4339495
// flow-typed version: <<STUB>>/node-stylus-css-modules-require_v^0.3.2/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-stylus-css-modules-require'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-stylus-css-modules-require' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'node-stylus-css-modules-require/src/index' {
  declare module.exports: any;
}

declare module 'node-stylus-css-modules-require/src/stylus-require' {
  declare module.exports: any;
}

declare module 'node-stylus-css-modules-require/tests/test-spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'node-stylus-css-modules-require/src/index.js' {
  declare module.exports: $Exports<'node-stylus-css-modules-require/src/index'>;
}
declare module 'node-stylus-css-modules-require/src/stylus-require.js' {
  declare module.exports: $Exports<'node-stylus-css-modules-require/src/stylus-require'>;
}
declare module 'node-stylus-css-modules-require/tests/test-spec.js' {
  declare module.exports: $Exports<'node-stylus-css-modules-require/tests/test-spec'>;
}
