// flow-typed signature: b9e34b1ee7030a40e532e3c9226d2945
// flow-typed version: <<STUB>>/r-swipeable_v^1.2.0-rc4/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'r-swipeable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'r-swipeable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'r-swipeable/flow-typed/npm/babel-cli_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-core_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-loader_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-preset-es2015_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-preset-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/babel-preset-stage-0_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/chai_v3.5.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint-config-google_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint-config-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint-config-standard-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint-plugin-promise_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint-plugin-react_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/eslint-plugin-standard_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/flow-bin_v0.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/flow-typed_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/inline-style-prefixer_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/jsdom_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/mocha_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/react-addons-test-utils_v15.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/webpack_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/flow-typed/npm/webpack-dev-server_vx.x.x' {
  declare module.exports: any;
}

declare module 'r-swipeable/lib/index' {
  declare module.exports: any;
}

declare module 'r-swipeable/lib/style' {
  declare module.exports: any;
}

declare module 'r-swipeable/lib/swipeable' {
  declare module.exports: any;
}

declare module 'r-swipeable/src/index' {
  declare module.exports: any;
}

declare module 'r-swipeable/src/style' {
  declare module.exports: any;
}

declare module 'r-swipeable/src/swipeable' {
  declare module.exports: any;
}

declare module 'r-swipeable/test/index' {
  declare module.exports: any;
}

declare module 'r-swipeable/test/swipeable-app' {
  declare module.exports: any;
}

declare module 'r-swipeable/test/swipeable/mount-test' {
  declare module.exports: any;
}

declare module 'r-swipeable/test/test-helper' {
  declare module.exports: any;
}

declare module 'r-swipeable/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'r-swipeable/flow-typed/npm/babel-cli_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-cli_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-core_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-core_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-eslint_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-eslint_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-loader_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-loader_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-plugin-transform-runtime_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-preset-es2015_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-preset-es2015_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-preset-react_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-preset-react_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/babel-preset-stage-0_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/babel-preset-stage-0_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/chai_v3.5.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/chai_v3.5.x'>;
}
declare module 'r-swipeable/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint-config-google_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint-config-google_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint-config-standard_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint-config-standard_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint-config-standard-react_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint-config-standard-react_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint-plugin-promise_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint-plugin-promise_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint-plugin-react_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint-plugin-react_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/eslint-plugin-standard_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/eslint-plugin-standard_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/flow-bin_v0.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/flow-bin_v0.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/flow-typed_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/flow-typed_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/inline-style-prefixer_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/inline-style-prefixer_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/jsdom_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/jsdom_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/mocha_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/mocha_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/react-addons-test-utils_v15.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/react-addons-test-utils_v15.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/webpack_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/webpack_vx.x.x'>;
}
declare module 'r-swipeable/flow-typed/npm/webpack-dev-server_vx.x.x.js' {
  declare module.exports: $Exports<'r-swipeable/flow-typed/npm/webpack-dev-server_vx.x.x'>;
}
declare module 'r-swipeable/lib/index.js' {
  declare module.exports: $Exports<'r-swipeable/lib/index'>;
}
declare module 'r-swipeable/lib/style.js' {
  declare module.exports: $Exports<'r-swipeable/lib/style'>;
}
declare module 'r-swipeable/lib/swipeable.js' {
  declare module.exports: $Exports<'r-swipeable/lib/swipeable'>;
}
declare module 'r-swipeable/src/index.js' {
  declare module.exports: $Exports<'r-swipeable/src/index'>;
}
declare module 'r-swipeable/src/style.js' {
  declare module.exports: $Exports<'r-swipeable/src/style'>;
}
declare module 'r-swipeable/src/swipeable.js' {
  declare module.exports: $Exports<'r-swipeable/src/swipeable'>;
}
declare module 'r-swipeable/test/index.js' {
  declare module.exports: $Exports<'r-swipeable/test/index'>;
}
declare module 'r-swipeable/test/swipeable-app.js' {
  declare module.exports: $Exports<'r-swipeable/test/swipeable-app'>;
}
declare module 'r-swipeable/test/swipeable/mount-test.js' {
  declare module.exports: $Exports<'r-swipeable/test/swipeable/mount-test'>;
}
declare module 'r-swipeable/test/test-helper.js' {
  declare module.exports: $Exports<'r-swipeable/test/test-helper'>;
}
declare module 'r-swipeable/webpack.config.js' {
  declare module.exports: $Exports<'r-swipeable/webpack.config'>;
}
